better async
  * apollo-export now uses async transcoding and archiving, resulting in
    massive speedups.
  * async system fully reworked. Still fairly complex, but no more weird
    datakinds for every async job. Instead we use a typeclass MonadJob and
    RankNTypes to pass around polymorphic actions in this monad. These can be
    interpreted with concrete monads to get different effects. For instance,
    interpreting in the RunJob monad stores the progress reports of the job
    inside an IORef held in a JobBank, whereas interpreting in the NoProgress
    monad ignores progress reports. The former is used to implement
    asynchronously running jobs, whereas the latter is used to run jobs
    synchronously. This allows us to reuse the *exact* same code in both cases.

diff --git a/apollo-scripts/bin/apollo-export b/apollo-scripts/bin/apollo-export
--- a/apollo-scripts/bin/apollo-export
+++ b/apollo-scripts/bin/apollo-export
@@ -25,6 +25,7 @@ require() {
 require jq
 require curl
 require wc
+require wget
 
 get() {
   # echo "GET $1" >&2
@@ -37,11 +38,9 @@ post() {
 }
 
 PLAYLIST="$(mktemp)"
-ARCHIVEREQ="$(mktemp)"
 
 cleanup() {
   rm "$PLAYLIST"
-  rm "$ARCHIVEREQ"
 }
 
 trap cleanup EXIT
@@ -50,18 +49,16 @@ trap cleanup EXIT
 get /playlist | jq .tracks[].path > "$PLAYLIST"
 $EDITOR "$PLAYLIST"
 
-TOTAL=$(cat "$PLAYLIST" | wc -l)
+PLAYLIST_TOTAL=$(cat "$PLAYLIST" | wc -l)
+
+if [ $PLAYLIST_TOTAL -eq 0 ] ; then
+    echo 'Nothing to do.'
+    exit 0
+fi
 
 # sends a transcode request for the track, and prints its trackId
 transcode() {
-  local TRACK="$1"
-  post /transcode "{ \"source\": $TRACK, \"params\": $PARAMS }" | jq .trackId
-}
-
-transcode_failed() {
-  echo '' >&2
-  echo "Transcoding failed for track $1" >&2
-  exit 1
+  post /transcode/async "$1"
 }
 
 overwrite_stderr() {
@@ -70,29 +67,78 @@ overwrite_stderr() {
 
 update_progress() {
   local COMPLETE="$1"
+  local TOTAL="$2"
   overwrite_stderr
   echo -n "$COMPLETE / $TOTAL" >&2
 }
 
-archive() {
-  post /archive "$(cat "$ARCHIVEREQ")"
-}
+poll_async_progress() {
+    while true ; do
+        result="$(curl --fail -s "$1")"
+        stat="$(echo "$result" | jq -r .status)"
 
-get_archive() {
-  get /archive/$1
+        if [ "$stat" = "running" ] ; then
+            num="$(echo "$result" | jq -r .progress.done)"
+            total="$(echo "$result" | jq -r .progress.outOf)"
+            update_progress "$num" "$total"
+        else
+            break
+        fi
+    done
 }
 
 echo 'Transcoding...' >&2
-i=0
-cat "$PLAYLIST" | while read TRACK ; do
-  transcode "$TRACK" || transcode_failed "$TRACK"
-  i=$(( $i + 1 ))
-  update_progress $i
-done |
-jq -s "map({ type: \"transcode\", transParams: $PARAMS, trackId: . })" > "$ARCHIVEREQ"
 
-echo ''
-echo 'Transcoding complete.' >&2
+TRANSCODEREQ="$(
+    cat "$PLAYLIST" |
+    jq -s "map({ params: $PARAMS, source: . })"
+)"
 
-echo 'Archiving...' >&2
-archive | jq -r .archiveId | xargs -I {} curl "$URL/archive/{}" > apollo-export.zip
+queue="$(post /transcode/async "$TRANSCODEREQ")"
+query="$(echo "$queue" | jq -r .query)"
+jobId="$(echo "$queue" | jq -r .jobId)"
+
+echo "Asynchronously transcoding... (Job id ${jobId})" >&2
+
+poll_async_progress "$query"
+
+if [ "$stat" = "failed" ] ; then
+    echo ''
+    echo "Transcoding failed." >&2
+    exit 1
+elif [ "$stat" = "complete" ] ; then
+    ARCHIVEREQ="$(
+        echo "$result" |
+        jq .result |
+        jq -c "map({ transParams: $PARAMS, type: \"transcode\", trackId: . })"
+    )"
+    echo ''
+    echo "Transcoding complete." >&2
+else
+    echo "Unknown status." >&2
+    exit 1
+fi
+
+queue="$(post /archive/async "$ARCHIVEREQ")"
+query="$(echo "$queue" | jq -r .query)"
+jobId="$(echo "$queue" | jq -r .jobId)"
+
+echo "Asynchronously archiving... (Job id ${jobId})" >&2
+echo '' >&2
+
+poll_async_progress "$query"
+
+if [ "$stat" = "failed" ] ; then
+    echo ''
+    echo "Archiving failed." >&2
+    exit 1
+elif [ "$stat" = "complete" ] ; then
+    archiveId="$(echo "$result" | jq -r .result.archiveId)"
+    archiveUrl="$(echo "$result" | jq -r .result.archiveUrl)"
+    echo ''
+    echo "Archiving complete; created archive $archiveId" >&2
+    echo "Downloading..." >&2
+    wget "$archiveUrl"
+else
+    echo "Unknown status." >&2
+fi
